<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HomePage</title>
    <link rel="stylesheet" href="${"/static/styles/homePage.css"}">
</head>
<body>
<div class="page1">
    <p class="burgername">King Burger</p>
    <p class="name2">with various layers of delicious food into one.</p>
</div>

<form action="/admin" method="get">
    <button>перейти к панели админа</button>
</form>
</body>
</html>